name: example
description: Example application for demonstrating progress stepper

version: 1.3.0+4
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  progress_stepper:
    path: ../


flutter:

  uses-material-design: true
