name: example
description: Example application for demonstrating progress stepper

version: 1.1.0+2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  progress_stepper:
    path: ../


flutter:

  uses-material-design: true
