name: progress_stepper
description: Flutter package for showing custom progress stepper.
version: 0.0.1
author: Midhun MP<midhunmp7@gmail.com>
homepage: https://github.com/Midhun-MP/progress_stepper.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


